  import type { Metadata } from "next";
  import localFont from "next/font/local";
  import "./globals.css";
  import { ReactNode } from "react";
  import { AuthProvider } from "@/components/hooks/useContext";


  const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
    display: "swap",
  });
  const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
    display: "swap",
  });
  

  export const metadata: Metadata = {
    title: "BOOKING HOTEL",
    description: "Generated by create next app",
  };

  interface RootLayoutProps {
    children: ReactNode;  
  }
  export default function RootLayout({ children }: RootLayoutProps) {
    return (
      <html lang="en" >
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <AuthProvider>
            {children}
            </AuthProvider>
        </body>
      </html>
    );
  }

